## SOFTWARE
BCFTOOLS: "/home/krishang/software/bcftools/bcftools-1.13/bin/bcftools"
PLINK: "plink"
PYTHON: "/home/krishang/software/vir_python36/bin/python"
MSMC2: "/home/krishang/software/msmc2/msmc2"

## the software can take either VCF or PLINK BED file
VCF: "snps10M.6inds.filltag.phased.bosTau9_bos_variable_sites_nomultiallelics_noindels_10dp_3het.phased.bcf"
PHASED: 1 ## 1: yes 0: unphased
## OUTMAIN: "results"
OUTMAIN: "/home/users/xi/AsianBos_project/Bali_javanicus/msmc2_coalest_Bali_javanicus"
GOODBED: "autosome_rep_het_dep_map.bed"
FAI: "bosTau9_plusY.fasta.fai"
MUT: 1.54e-8
GEN: 7
POPS:
  Bali_cattle_Indonesia: Bali_cattle_Indonesia.group
  Bos_javanicus: Bos_javanicus.group
CHROMS:
  - NC_037328.1
  - NC_037329.1
  - NC_037330.1
  - NC_037331.1
  - NC_037332.1
  - NC_037333.1
  - NC_037334.1
  - NC_037335.1
  - NC_037336.1
  - NC_037337.1
  - NC_037338.1
  - NC_037339.1
  - NC_037340.1
  - NC_037341.1
  - NC_037342.1
  - NC_037343.1
  - NC_037344.1
  - NC_037345.1
  - NC_037346.1
  - NC_037347.1
  - NC_037348.1
  - NC_037349.1
  - NC_037350.1
  - NC_037351.1
  - NC_037352.1
  - NC_037353.1
  - NC_037354.1
  - NC_037355.1
  - NC_037356.1
